### PR TITLE
bridge: be tolerant to missing references

### LINKED ISSUE #80: BridgeException: Cannot find the referenced element
**Replicate**

1. Create an SVG file with an unused reference. This can happen by editing an SVG created in Adobe Illustrator with Inkscape and removing objects. See [e.svg.txt](https://github.com/css4j/echosvg/files/11729942/e.svg.txt). Essentially:

   ``` xml
   <clipPath
     id="SVGID_00000145770309263158979710000005844928936766913719_">
   <use
     xlink:href="#SVGID_00000072257059765744298700000011011170644502566322_"
     id="use3" />
   </clipPath>
   ```

1. Rasterize the file using EchoSVG.

**Expected**

The unused reference is ignored and rasterizing continues. This is the behaviour that Inkscape takes, which permits it to load the image:

e

**Actual**

Exception is thrown and the image is not rasterized.

```
io.sf.carte.echosvg.bridge.BridgeException: file:community.svg:-1
Cannot find the referenced element:
"#SVGID_00000072257059765744298700000011011170644502566322_"
specified on the element <use> - may be a problem of 'id'
```

The root cause is `BridgeContext.java`, line 752, where it is assumed incorrectly that all such `Element` instances have a valid `Node` reference:

``` java
Node ref = ur.getNode(uri, e);
if (ref == null) {
  throw new BridgeException(this, e, ERR_URI_BAD_TARGET, new Object[] { uri });
```

This exception is caught by `SVGAbstractTransformer` at line 261 and wrapped into a new exception:

```
throw new TranscoderException(ex);
```

By the time it is wrapped and re-thrown as a `TranscoderException`, it's too late to intervene. Perhaps instead of creating a `BridgeException`, there needs to be an `UndefinedReferenceException` subclass of `BridgeException`? That way the exception can still be caught by `SVGAbstractTransformer` yet passed along to the `ErrorHandler` instead of being wrapped and re-thrown?

Another idea would be to create an "Empty" node/element to represent a missing reference, but that would needlessly clutter the DOM or have any number of unintended side-effects, I imagine, because `getReferencedNode` is used in many places.

### PR DESCRIPTION
**Pull request by carlosame**
Instead of throwing an exception (and stop processing) on a missing reference, just report the error via the user agent and keep processing. This is what a conformant user agent is supposed to do.

There are other circumstances (like other I/O errors) where it would make sense to behave in the same way, but this may break [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) for legacy applications and is deferred to future updates. User feedback is encouraged.

The `slideshow` and `extension` modules are also affected by this PR.

Fixes #80.

### CODE REVIEW

File: echosvg-bridge/src/main/java/io/sf/carte/echosvg/bridge/SVGAnimationElementBridge.java [hunk 1]
```diff
@@ -164,7 +164,7 @@ protected void initializeAnimation() {
 			t = element.getParentNode();
 		} else {
 			t = ctx.getReferencedElement(element, uri);
-			if (t.getOwnerDocument() != element.getOwnerDocument()) {
+			if (t == null || t.getOwnerDocument() != element.getOwnerDocument()) {
```
Comment (DaveJarvis) [inline echosvg-bridge/src/main/java/io/sf/carte/echosvg/bridge/SVGAnimationElementBridge.java:167]: Won't this still throw an exception when the referenced element cannot be found?

File: echosvg-bridge/src/main/java/io/sf/carte/echosvg/bridge/SVGUtilities.java [hunk 2]
```diff
@@ -265,6 +266,15 @@ public static String getChainableAttributeNS(Element element, String namespaceUR
 				URIResolver resolver = ctx.createURIResolver(svgDoc, loader);
 				e = resolver.getElement(purl.toString(), e);
 				refs.add(purl);
+			} catch (FileNotFoundException ioEx) {
+				BridgeException ex = new BridgeException(ctx, e, ioEx, ERR_URI_IO,
```
Comment (DaveJarvis) [inline echosvg-bridge/src/main/java/io/sf/carte/echosvg/bridge/SVGUtilities.java:270]: What do you think about isolating this duplicated code, possibly by delegating to the `UserAgent` using a static method?

``` java
catch(final FileNotFoundException fnfEx) {
  final BridgeExceptoin ex = new BridgeException(...);
  UserAgent.handle( ex, ctx );
  return "";
}
```

Doesn't have to go to the `UserAgent`, but it would be nice to see the duplication in one spot.

File: echosvg-bridge/src/main/java/io/sf/carte/echosvg/bridge/SVGAnimationElementBridge.java (hunk 1 above)
Comment (carlosame) [reply echosvg-bridge/src/main/java/io/sf/carte/echosvg/bridge/SVGAnimationElementBridge.java:170]: Done in ba1fbcd2566db2dba3f96ffc65e57705bb4e91fa
